### ISSUE TITLE
Bug when simu does not match expected length

### ISSUE THREAD

**Issue by pmathiot** [jbbarre/ISM_SimulationChecker#16]
Script error when detecting simu longer than expected (287 instead of 286) :
```
Traceback (most recent call last):
  File "/ccc/workflash/cont003/gen6035/mathiotp/TOOLS/ISM_SimulationChecker/compliance_checker.py", line 431, in <module>
    end_date = start_exp  + datetime.timedelta(days = experiments[index_exp]['duration']*avgyear)
numpy.core._exceptions._UFuncBinaryResolutionError: ufunc 'add' cannot use operands with types dtype('<M8[D]') and dtype('O')
```

Output of start_exp is 2015-07-02 and datetime.timedelta(days = experiments[index_exp]['duration']*avgyear) 104459 days, 8:31:12

**Comment by jbbarre** [comment]
The end_date varaible is now calculated only with numpy format:
`end_date = start_exp  + np.timedelta64(experiments[2]['duration']*365,'D')`
