### ISSUE TITLE
Time length is not correct.

### ISSUE THREAD

**Issue by pmathiot** [jbbarre/ISM_SimulationChecker#6]
The ISMIP6 extension should be 286y and stop in 2300 if I am not wrong. When running the sanity check, it appears that a time error was detected for my file with 286 time frame and an expect end of the experiments in 2101.

```
 - ERROR: the experiment lasts 286 years. The duration should be 86 years
 - As the experiment started on 2016-01-01 , it should end on 2101-12-31
```

**Comment by jbbarre** [comment]
Different experiment setups are in available. You need to modify the experiment variable to select the correct experiment setup. 
The current standard value is `experiments = experiments_ismip6_ext`
