### ISSUE TITLE
Comments on data range

### ISSUE THREAD

**Issue by pmathiot** [jbbarre/ISM_SimulationChecker#7]
I know those values are indicative and should not prevent pushing the data if the tests on value are broken but the less errors we have for good reason, the better it is I think.
* base: min value is -3000. In Bedmachine, I found a point under the ice sheet at -3710m (under Amery glacier), so probably -4000m is more reasonable than -3000m.
* ligroundf: max value accepted is 0. This test is broken as soon as you have a pinning point in the model (ice is coming inside upstream of the pinning point (+ sign) and outside downstream of the pinning point (- sign)). I suggest to have the same sanity check on min and max and check the integrated value to detect error on the sign convention (should be negative).

**Comment by hseroussi** [comment]
I updated the value for base to be -4000m to avoid that problem.
I also updated ligroundf to a relatively small value to limit this problem, however the goal was mostly to check the sign of the field to make sure it was consistent with the description, so we won't put it to the same range as the maximum. We have not developed test for integrated value, it would be great be beyond what we could do for this version.
